#!/bin/bash

echo -e "Clean State..\n"
killall logmon
rmmod syswatch

gcc -O2 -c syswatch.c

./bin/build_ldev

echo -e "Compiling..\n"
gcc -O2 -o ./bin/logmon ./bin/logmon.c -lpthread -I/usr/local/mysql/include/mysql -L/usr/local/mysql/lib/mysql -lmysqlclient
gcc -O2 -o ./bin/make_db ./bin/make_db.c -I/usr/local/mysql/include/mysql -L/usr/local/mysql/lib/mysql -lmysqlclient
gcc -O2 -o ./bin/drop_db ./bin/drop_db.c -I/usr/local/mysql/include/mysql -L/usr/local/mysql/lib/mysql -lmysqlclient
gcc -O2 -o ./bin/lshack ./bin/lshack.c -I/usr/local/mysql/include/mysql -L/usr/local/mysql/lib/mysql -lmysqlclient

echo -e "Enable Module..\n"
insmod syswatch.o

echo -e "Enable Logmon.. ^^a\n"
cd ./bin
./start
